//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pushnotifications
    {
        public int id { get; set; }
        public int eventid { get; set; }
        public int travelerid { get; set; }
        public bool sent { get; set; }
        public string token { get; set; }
    }
}
