//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stakeholders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stakeholders()
        {
            this.tblComments = new HashSet<tblComments>();
            this.tblEvents = new HashSet<tblEvents>();
            this.tblAskForHelp = new HashSet<tblAskForHelp>();
            this.tblConversationTravelerStack = new HashSet<tblConversationTravelerStack>();
            this.traveleres = new HashSet<traveleres>();
        }
    
        public int stakeholder_id { get; set; }
        public string full_name { get; set; }
        public string stakeholder_email { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<bool> notifications { get; set; }
        public Nullable<bool> chat { get; set; }
        public string stakeholder_name { get; set; }
        public Nullable<bool> approved { get; set; }
        public System.DateTime approvel_date { get; set; }
        public string stakeholder_type { get; set; }
        public string password { get; set; }
        public string picture { get; set; }
        public string token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComments> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvents> tblEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAskForHelp> tblAskForHelp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversationTravelerStack> tblConversationTravelerStack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traveleres> traveleres { get; set; }
    }
}
