//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvents()
        {
            this.tblComments = new HashSet<tblComments>();
        }
    
        public int eventNumber { get; set; }
        public string details { get; set; }
        public System.DateTime event_date { get; set; }
        public System.TimeSpan event_time { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<bool> event_status { get; set; }
        public string picture { get; set; }
        public Nullable<int> travelerId { get; set; }
        public Nullable<int> stackholderId { get; set; }
        public int serialTypeNumber { get; set; }
        public int country_number { get; set; }
        public int area_number { get; set; }
        public string is_related { get; set; }
        public string approved { get; set; }
        public string not_approved { get; set; }
        public string labels { get; set; }
    
        public virtual stakeholders stakeholders { get; set; }
        public virtual tblArea tblArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComments> tblComments { get; set; }
        public virtual traveleres traveleres { get; set; }
        public virtual tblEvents tblEvents1 { get; set; }
        public virtual tblEvents tblEvents2 { get; set; }
        public virtual tblType tblType { get; set; }
    }
}
