//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travelere()
        {
            this.tblAskForHelps = new HashSet<tblAskForHelp>();
            this.tblComments = new HashSet<tblComment>();
            this.tblEvents = new HashSet<tblEvent>();
            this.tblLocations = new HashSet<tblLocation>();
            this.tblConversationTravelerStacks = new HashSet<tblConversationTravelerStack>();
            this.tblConversationTravelers = new HashSet<tblConversationTraveler>();
            this.tblConversationTravelers1 = new HashSet<tblConversationTraveler>();
            this.stakeholders = new HashSet<stakeholder>();
        }
    
        public int traveler_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string travler_email { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<bool> notifications { get; set; }
        public string insurence_company { get; set; }
        public Nullable<bool> location { get; set; }
        public Nullable<bool> save_location { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string gender { get; set; }
        public string password { get; set; }
        public Nullable<bool> chat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAskForHelp> tblAskForHelps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComment> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvent> tblEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversationTravelerStack> tblConversationTravelerStacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversationTraveler> tblConversationTravelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversationTraveler> tblConversationTravelers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stakeholder> stakeholders { get; set; }
    }
}
